<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="MVVM\Models\" />
    <Folder Include="MVVM\ViewModels\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\main_logo.ico" Condition="Exists('Assets\main_logo.ico')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\main_logo.png" Condition="Exists('Assets\main_logo.png')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Logo\logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Logo\FBG_App_Icon_MAX.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Logo\main_logo.png" Condition="Exists('Assets\Logo\main_logo.png')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Logo\main_logo_transparent.png" Condition="Exists('Assets\Logo\main_logo_transparent.png')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Logo\FBG_App_Icon.ico" Condition="Exists('Assets\Logo\FBG_App_Icon.ico')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Logo\main_logo.ico" Condition="Exists('Assets\Logo\main_logo.ico')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Logo\main_logo_transparent.ico" Condition="Exists('Assets\Logo\main_logo_transparent.ico')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.5" />
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
    <PackageReference Include="Wpf.Ui" Version="3.4.2.7">
      <IncludeAssets>all</IncludeAssets>
      <PrivateAssets>none</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
